apiVersion: v1
kind: Pod
metadata:
  name: cpuload
spec:
  containers:
  - name: loader-1
    image: bjosv/cpuload:latest
    env:
    - name: HOG_SECONDS
      value: "1"
    - name: IDLE_SECONDS
      value: "9"
    resources:
      limits:
        cpu: "1000m"
      requests:
        cpu: "100m"
  # - name: loader-2
  #   image: bjosv/cpuload:latest
  #   env:
  #   - name: HOG_SECONDS
  #     value: "1"
  #   - name: IDLE_SECONDS
  #     value: "9"
  #   resources:
  #     limits:
  #       cpu: "1000m"
  #     requests:
  #       cpu: "100m"
